services:
  ap-server:
    build: .
    image: ap-server
    ports:
      - ${LTI_SERVER_PORT:-9002}:8000
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - TOKEN_SECRET=secret
    volumes:
      - fluentd-data:/fluentd/log:ro
    depends_on:
      - postgres
      - fluentd

  postgres:
    image: postgres:9.6.6
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
    - "5422:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - LOG_LEVEL=DEBUG

  fluentd:
    image: fluent/fluentd:v1.17
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf/fluentd.conf:/fluentd/etc/fluentd.conf
      - fluentd-data:/fluentd/log
    environment:
      - FLUENTD_CONF=fluentd.conf
    entrypoint: >
      sh -c "rm -f /fluentd/log/* && exec fluentd -c /fluentd/etc/fluentd.conf"

  tunnel:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-tls-verify --url https://ap-server:8000"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: cloudflared
    depends_on:
      - fluentd

volumes:
  fluentd-data:
